# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_demo_1.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(938, 769)
        self.formGroupBox = QtWidgets.QGroupBox(Form)
        self.formGroupBox.setGeometry(QtCore.QRect(690, 10, 171, 311))
        self.formGroupBox.setObjectName("formGroupBox")
        self.formLayout = QtWidgets.QFormLayout(self.formGroupBox)
        self.formLayout.setContentsMargins(10, 10, 10, 10)
        self.formLayout.setSpacing(10)
        self.formLayout.setObjectName("formLayout")
        self.s1__box_1 = QtWidgets.QPushButton(self.formGroupBox)
        self.s1__box_1.setAutoRepeatInterval(100)
        self.s1__box_1.setDefault(True)
        self.s1__box_1.setObjectName("s1__box_1")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.s1__box_1)
        self.s1__lb_2 = QtWidgets.QLabel(self.formGroupBox)
        self.s1__lb_2.setObjectName("s1__lb_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.s1__lb_2)
        self.s1__box_2 = QtWidgets.QComboBox(self.formGroupBox)
        self.s1__box_2.setObjectName("s1__box_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.s1__box_2)
        self.state_label = QtWidgets.QLabel(self.formGroupBox)
        self.state_label.setText("")
        self.state_label.setTextFormat(QtCore.Qt.AutoText)
        self.state_label.setScaledContents(True)
        self.state_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.state_label.setObjectName("state_label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.state_label)
        self.s1__lb_3 = QtWidgets.QLabel(self.formGroupBox)
        self.s1__lb_3.setObjectName("s1__lb_3")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.s1__lb_3)
        self.s1__box_3 = QtWidgets.QComboBox(self.formGroupBox)
        self.s1__box_3.setObjectName("s1__box_3")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.s1__box_3.addItem("")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.s1__box_3)
        self.s1__lb_4 = QtWidgets.QLabel(self.formGroupBox)
        self.s1__lb_4.setObjectName("s1__lb_4")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.s1__lb_4)
        self.s1__box_4 = QtWidgets.QComboBox(self.formGroupBox)
        self.s1__box_4.setObjectName("s1__box_4")
        self.s1__box_4.addItem("")
        self.s1__box_4.addItem("")
        self.s1__box_4.addItem("")
        self.s1__box_4.addItem("")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.s1__box_4)
        self.s1__lb_5 = QtWidgets.QLabel(self.formGroupBox)
        self.s1__lb_5.setObjectName("s1__lb_5")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.s1__lb_5)
        self.s1__box_5 = QtWidgets.QComboBox(self.formGroupBox)
        self.s1__box_5.setObjectName("s1__box_5")
        self.s1__box_5.addItem("")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.s1__box_5)
        self.s1__lb_6 = QtWidgets.QLabel(self.formGroupBox)
        self.s1__lb_6.setObjectName("s1__lb_6")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.s1__lb_6)
        self.s1__box_6 = QtWidgets.QComboBox(self.formGroupBox)
        self.s1__box_6.setObjectName("s1__box_6")
        self.s1__box_6.addItem("")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.s1__box_6)
        self.open_button = QtWidgets.QPushButton(self.formGroupBox)
        self.open_button.setObjectName("open_button")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.SpanningRole, self.open_button)
        self.close_button = QtWidgets.QPushButton(self.formGroupBox)
        self.close_button.setObjectName("close_button")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.SpanningRole, self.close_button)
        self.s1__lb_1 = QtWidgets.QLabel(self.formGroupBox)
        self.s1__lb_1.setObjectName("s1__lb_1")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.s1__lb_1)
        self.verticalGroupBox = QtWidgets.QGroupBox(Form)
        self.verticalGroupBox.setGeometry(QtCore.QRect(460, 420, 401, 241))
        self.verticalGroupBox.setObjectName("verticalGroupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalGroupBox)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.s2__receive_text = QtWidgets.QTextBrowser(self.verticalGroupBox)
        self.s2__receive_text.setObjectName("s2__receive_text")
        self.verticalLayout.addWidget(self.s2__receive_text)
        self.formGroupBox1 = QtWidgets.QGroupBox(Form)
        self.formGroupBox1.setGeometry(QtCore.QRect(690, 320, 171, 71))
        self.formGroupBox1.setObjectName("formGroupBox1")
        self.formLayout_2 = QtWidgets.QFormLayout(self.formGroupBox1)
        self.formLayout_2.setContentsMargins(10, 10, 10, 10)
        self.formLayout_2.setSpacing(10)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label = QtWidgets.QLabel(self.formGroupBox1)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.formGroupBox1)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.hex_receive = QtWidgets.QCheckBox(Form)
        self.hex_receive.setGeometry(QtCore.QRect(770, 680, 81, 16))
        self.hex_receive.setObjectName("hex_receive")
        self.s2__clear_button = QtWidgets.QPushButton(Form)
        self.s2__clear_button.setGeometry(QtCore.QRect(790, 710, 61, 31))
        self.s2__clear_button.setObjectName("s2__clear_button")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(0, 10, 431, 451))
        self.groupBox.setObjectName("groupBox")
        self.messi = QtWidgets.QLabel(self.groupBox)
        self.messi.setGeometry(QtCore.QRect(10, 30, 411, 411))
        self.messi.setFrameShape(QtWidgets.QFrame.Box)
        self.messi.setText("")
        self.messi.setObjectName("messi")
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(440, 10, 221, 401))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_ip = QtWidgets.QLabel(self.groupBox_2)
        self.label_ip.setGeometry(QtCore.QRect(10, 20, 61, 21))
        self.label_ip.setObjectName("label_ip")
        self.lineEdit_ip_local = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_ip_local.setGeometry(QtCore.QRect(72, 20, 131, 21))
        self.lineEdit_ip_local.setObjectName("lineEdit_ip_local")
        self.pushButton_get_ip = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_get_ip.setGeometry(QtCore.QRect(20, 50, 171, 31))
        self.pushButton_get_ip.setObjectName("pushButton_get_ip")
        self.label_port = QtWidgets.QLabel(self.groupBox_2)
        self.label_port.setGeometry(QtCore.QRect(10, 90, 71, 21))
        self.label_port.setObjectName("label_port")
        self.lineEdit_port = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_port.setGeometry(QtCore.QRect(80, 90, 121, 21))
        self.lineEdit_port.setObjectName("lineEdit_port")
        self.lineEdit_ip = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_ip.setGeometry(QtCore.QRect(72, 120, 131, 21))
        self.lineEdit_ip.setObjectName("lineEdit_ip")
        self.label_sendto = QtWidgets.QLabel(self.groupBox_2)
        self.label_sendto.setGeometry(QtCore.QRect(10, 120, 71, 21))
        self.label_sendto.setObjectName("label_sendto")
        self.pushButton_link = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_link.setGeometry(QtCore.QRect(10, 150, 93, 28))
        self.pushButton_link.setObjectName("pushButton_link")
        self.pushButton_unlink = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_unlink.setGeometry(QtCore.QRect(120, 150, 93, 28))
        self.pushButton_unlink.setObjectName("pushButton_unlink")
        self.textBrowser_recv = QtWidgets.QTextBrowser(self.groupBox_2)
        self.textBrowser_recv.setGeometry(QtCore.QRect(10, 190, 201, 201))
        self.textBrowser_recv.setObjectName("textBrowser_recv")
        self.open_camera = QtWidgets.QPushButton(Form)
        self.open_camera.setGeometry(QtCore.QRect(110, 530, 93, 28))
        self.open_camera.setObjectName("open_camera")
        self.yolov3 = QtWidgets.QPushButton(Form)
        self.yolov3.setGeometry(QtCore.QRect(300, 530, 121, 28))
        self.yolov3.setObjectName("yolov3")
        self.close_camera = QtWidgets.QPushButton(Form)
        self.close_camera.setGeometry(QtCore.QRect(110, 570, 93, 28))
        self.close_camera.setObjectName("close_camera")
        self.close_yolov3 = QtWidgets.QPushButton(Form)
        self.close_yolov3.setGeometry(QtCore.QRect(300, 570, 121, 28))
        self.close_yolov3.setObjectName("close_yolov3")
        self.verticalGroupBox.raise_()
        self.formGroupBox.raise_()
        self.formGroupBox.raise_()
        self.hex_receive.raise_()
        self.s2__clear_button.raise_()
        self.groupBox.raise_()
        self.groupBox_2.raise_()
        self.open_camera.raise_()
        self.yolov3.raise_()
        self.close_camera.raise_()
        self.close_yolov3.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.formGroupBox.setTitle(_translate("Form", "串口设置"))
        self.s1__box_1.setText(_translate("Form", "检测串口"))
        self.s1__lb_2.setText(_translate("Form", "串口选择："))
        self.s1__lb_3.setText(_translate("Form", "波特率："))
        self.s1__box_3.setItemText(0, _translate("Form", "115200"))
        self.s1__box_3.setItemText(1, _translate("Form", "2400"))
        self.s1__box_3.setItemText(2, _translate("Form", "4800"))
        self.s1__box_3.setItemText(3, _translate("Form", "9600"))
        self.s1__box_3.setItemText(4, _translate("Form", "14400"))
        self.s1__box_3.setItemText(5, _translate("Form", "19200"))
        self.s1__box_3.setItemText(6, _translate("Form", "38400"))
        self.s1__box_3.setItemText(7, _translate("Form", "57600"))
        self.s1__box_3.setItemText(8, _translate("Form", "76800"))
        self.s1__box_3.setItemText(9, _translate("Form", "12800"))
        self.s1__box_3.setItemText(10, _translate("Form", "230400"))
        self.s1__box_3.setItemText(11, _translate("Form", "460800"))
        self.s1__lb_4.setText(_translate("Form", "数据位："))
        self.s1__box_4.setItemText(0, _translate("Form", "8"))
        self.s1__box_4.setItemText(1, _translate("Form", "7"))
        self.s1__box_4.setItemText(2, _translate("Form", "6"))
        self.s1__box_4.setItemText(3, _translate("Form", "5"))
        self.s1__lb_5.setText(_translate("Form", "校验位："))
        self.s1__box_5.setItemText(0, _translate("Form", "N"))
        self.s1__lb_6.setText(_translate("Form", "停止位："))
        self.s1__box_6.setItemText(0, _translate("Form", "1"))
        self.open_button.setText(_translate("Form", "打开串口"))
        self.close_button.setText(_translate("Form", "关闭串口"))
        self.s1__lb_1.setText(_translate("Form", "串口检测："))
        self.verticalGroupBox.setTitle(_translate("Form", "接受区"))
        self.formGroupBox1.setTitle(_translate("Form", "串口状态"))
        self.label.setText(_translate("Form", "已接收："))
        self.hex_receive.setText(_translate("Form", "Hex接收"))
        self.s2__clear_button.setText(_translate("Form", "清除"))
        self.groupBox.setTitle(_translate("Form", "显示区"))
        self.groupBox_2.setTitle(_translate("Form", "网络设置"))
        self.label_ip.setText(_translate("Form", "本机IP："))
        self.pushButton_get_ip.setText(_translate("Form", "重新获取IP"))
        self.label_port.setText(_translate("Form", "目标端口："))
        self.label_sendto.setText(_translate("Form", "目标IP："))
        self.pushButton_link.setText(_translate("Form", "连接网络"))
        self.pushButton_unlink.setText(_translate("Form", "断开网络"))
        self.open_camera.setText(_translate("Form", "开启摄像头"))
        self.yolov3.setText(_translate("Form", "开启目标检测"))
        self.close_camera.setText(_translate("Form", "关闭摄像头"))
        self.close_yolov3.setText(_translate("Form", "关闭目标检测"))

